buildscript {
    repositories {
        maven {
            url = 'https://www.artifactrepository.citigroup.net:443/artifactory/maven-prod'
            credentials {
                username = providers
                        .gradleProperty('artifactory_user')
                        .orElse(providers.environmentVariable('ARTIFACTORY_USER'))
                        .getOrElse('')
                password = providers
                        .gradleProperty('artifactory_password')
                        .orElse(providers.environmentVariable('ARTIFACTORY_PASSWORD'))
                        .getOrElse('')
            }
        }
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:4.0.0'
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'

group = 'net.domax'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.0.0')
    annotationProcessor platform('org.springframework.boot:spring-boot-dependencies:4.0.0')
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:4.0.0')

    implementation 'org.springframework.boot:spring-boot-starter'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
